
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class LOGIN_JAVIS extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN_JAVIS
     */
    
    
    public LOGIN_JAVIS() {
        initComponents();
        Image i;
        try {
            i = ImageIO.read(getClass().getResource("Icons\\JAVIS_icon 512x512.png"));
            setIconImage(i);
        } catch (IOException ex) {
            Logger.getLogger(LOGIN_JAVIS.class.getName()).log(Level.SEVERE, null, ex);
        }

        jPback.setBackground(new Color(47,54,64,80));
        jPlogin.setBackground(new Color(53,59,72,190));
        jTFuser.setCaretPosition(0);
        jPFpass.setEchoChar((char)0);
        jTFuser.setBackground(new Color(0,0,0,0));
        jPFpass.setBackground(new Color(0,0,0,0));
        jTBTNvis.setBackground(new Color(0,0,0,0));
        jTBTNvis.setBorderPainted(false);
        jBTNforgotpass.setBorderPainted(false);
        jBTNforgotpass.setBackground(new Color(0,0,0,0));
        jBTNsignin.setBackground(new Color(0,0,0,0));
        jBTNsignup.setBackground(new Color(0,0,0,0));
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN_JAVIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN_JAVIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN_JAVIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN_JAVIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPback = new javax.swing.JPanel();
        jPsignup = new javax.swing.JPanel();
        jLBLsignup = new javax.swing.JLabel();
        jBTNsignup = new javax.swing.JButton();
        jPlogin = new javax.swing.JPanel();
        jLBLlogin = new javax.swing.JLabel();
        jTFuser = new javax.swing.JTextField();
        jSuser = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPFpass = new javax.swing.JPasswordField();
        jSpass = new javax.swing.JSeparator();
        jTBTNvis = new javax.swing.JToggleButton();
        jBTNforgotpass = new javax.swing.JButton();
        jPsignin = new javax.swing.JPanel();
        jLBLsignin = new javax.swing.JLabel();
        jBTNsignin = new javax.swing.JButton();
        jLBLosk = new javax.swing.JLabel();
        jLBLexit = new javax.swing.JLabel();
        jLBLminimize = new javax.swing.JLabel();
        jLBLtaskbar = new javax.swing.JLabel();
        jLBLicon = new javax.swing.JLabel();
        jLBLdysc1 = new javax.swing.JLabel();
        jLBLdysc2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLBLback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPback.setBackground(new java.awt.Color(47, 54, 64));
        jPback.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPbackMouseDragged(evt);
            }
        });
        jPback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPbackMousePressed(evt);
            }
        });
        jPback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPsignup.setBackground(new java.awt.Color(34, 47, 62));
        jPsignup.setToolTipText("Create your personnel account");
        jPsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPsignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPsignupMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPsignupMouseReleased(evt);
            }
        });

        jLBLsignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Add_User_Male_32px_1.png"))); // NOI18N
        jLBLsignup.setToolTipText("Create your personnel account");
        jLBLsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBLsignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBLsignupMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLBLsignupMouseReleased(evt);
            }
        });

        jBTNsignup.setBackground(new java.awt.Color(47, 54, 64));
        jBTNsignup.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBTNsignup.setForeground(new java.awt.Color(200, 200, 200));
        jBTNsignup.setText("Sign Up");
        jBTNsignup.setToolTipText("Create your personnel account");
        jBTNsignup.setOpaque(false);
        jBTNsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBTNsignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBTNsignupMouseExited(evt);
            }
        });
        jBTNsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNsignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPsignupLayout = new javax.swing.GroupLayout(jPsignup);
        jPsignup.setLayout(jPsignupLayout);
        jPsignupLayout.setHorizontalGroup(
            jPsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPsignupLayout.createSequentialGroup()
                .addComponent(jBTNsignup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBLsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPsignupLayout.setVerticalGroup(
            jPsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBLsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBTNsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPback.add(jPsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jPlogin.setBackground(new java.awt.Color(53, 59, 72));

        jLBLlogin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLBLlogin.setForeground(new java.awt.Color(200, 200, 200));
        jLBLlogin.setText("Log In");

        jTFuser.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTFuser.setForeground(new java.awt.Color(125, 125, 125));
        jTFuser.setText("User Name");
        jTFuser.setToolTipText("Enter Your User Name");
        jTFuser.setBorder(null);
        jTFuser.setOpaque(false);
        jTFuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFuserMousePressed(evt);
            }
        });
        jTFuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFuserActionPerformed(evt);
            }
        });
        jTFuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFuserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFuserKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Male_User_96px_4.png"))); // NOI18N

        jPFpass.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPFpass.setForeground(new java.awt.Color(125, 125, 125));
        jPFpass.setText("Password");
        jPFpass.setToolTipText("Enter Your Password");
        jPFpass.setBorder(null);
        jPFpass.setOpaque(false);
        jPFpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPFpassMousePressed(evt);
            }
        });
        jPFpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFpassActionPerformed(evt);
            }
        });
        jPFpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPFpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFpassKeyReleased(evt);
            }
        });

        jTBTNvis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Eye_32px_1.png"))); // NOI18N
        jTBTNvis.setToolTipText("Show/Hide Password");
        jTBTNvis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2));
        jTBTNvis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTBTNvisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTBTNvisMouseExited(evt);
            }
        });
        jTBTNvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBTNvisActionPerformed(evt);
            }
        });

        jBTNforgotpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Forgot_Password_32px_2.png"))); // NOI18N
        jBTNforgotpass.setToolTipText("Secured With End to End Encryption");
        jBTNforgotpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2));
        jBTNforgotpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBTNforgotpassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBTNforgotpassMouseExited(evt);
            }
        });

        jPsignin.setBackground(new java.awt.Color(34, 47, 62));
        jPsignin.setToolTipText("Sign In to your account");
        jPsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPsigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPsigninMouseExited(evt);
            }
        });

        jLBLsignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Login_32px_1.png"))); // NOI18N
        jLBLsignin.setToolTipText("Sign In to your account ");
        jLBLsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBLsigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBLsigninMouseExited(evt);
            }
        });

        jBTNsignin.setBackground(new java.awt.Color(47, 54, 64));
        jBTNsignin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBTNsignin.setForeground(new java.awt.Color(200, 200, 200));
        jBTNsignin.setText("Sign In");
        jBTNsignin.setToolTipText("Sign In to your Account");
        jBTNsignin.setOpaque(false);
        jBTNsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNsigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBTNsigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBTNsigninMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPsigninLayout = new javax.swing.GroupLayout(jPsignin);
        jPsignin.setLayout(jPsigninLayout);
        jPsigninLayout.setHorizontalGroup(
            jPsigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPsigninLayout.createSequentialGroup()
                .addComponent(jBTNsignin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBLsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPsigninLayout.setVerticalGroup(
            jPsigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBLsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jBTNsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLBLosk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Keyboard_64px.png"))); // NOI18N
        jLBLosk.setToolTipText("Use On Screen Keyboard");
        jLBLosk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBLoskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBLoskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBLoskMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPloginLayout = new javax.swing.GroupLayout(jPlogin);
        jPlogin.setLayout(jPloginLayout);
        jPloginLayout.setHorizontalGroup(
            jPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPloginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPloginLayout.createSequentialGroup()
                        .addComponent(jLBLlogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPloginLayout.createSequentialGroup()
                        .addGroup(jPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFuser, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                .addComponent(jSuser)
                                .addComponent(jSpass))
                            .addGroup(jPloginLayout.createSequentialGroup()
                                .addComponent(jPFpass, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTBTNvis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBTNforgotpass, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPloginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPsignin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(jPloginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBLosk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPloginLayout.setVerticalGroup(
            jPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPloginLayout.createSequentialGroup()
                .addGroup(jPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPloginLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLBLlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jTFuser, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSuser, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPloginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPFpass, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addComponent(jTBTNvis, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addComponent(jBTNforgotpass, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpass, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPsignin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLBLosk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPback.add(jPlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 420, 460));

        jLBLexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Cancel_32px.png"))); // NOI18N
        jLBLexit.setToolTipText("Exit");
        jLBLexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBLexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBLexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBLexitMouseExited(evt);
            }
        });
        jPback.add(jLBLexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 34, -1));

        jLBLminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Minimize_Window_32px_1.png"))); // NOI18N
        jLBLminimize.setToolTipText("Minimize");
        jLBLminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBLminimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBLminimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBLminimizeMouseExited(evt);
            }
        });
        jPback.add(jLBLminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));
        jPback.add(jLBLtaskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 32));

        jLBLicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/javis.png"))); // NOI18N
        jPback.add(jLBLicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 200, 50));

        jLBLdysc1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLBLdysc1.setForeground(new java.awt.Color(160, 160, 160));
        jLBLdysc1.setText("An all in one Environment");
        jPback.add(jLBLdysc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 300, 30));

        jLBLdysc2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLBLdysc2.setForeground(new java.awt.Color(160, 160, 160));
        jLBLdysc2.setText("for Knowledge and Fun");
        jPback.add(jLBLdysc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 270, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/JAVIS_icon_100x100.png"))); // NOI18N
        jPback.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 110, 110));

        getContentPane().add(jPback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        jLBLback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/launchit.gif"))); // NOI18N
        getContentPane().add(jLBLback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLBLexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLexitMouseEntered
    jLBLexit.setIcon(new ImageIcon(getClass().getClassLoader().getResource("Icons\\icons8_Cancel_32px_1.png")));
    }//GEN-LAST:event_jLBLexitMouseEntered

    private void jLBLexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLexitMouseExited
    jLBLexit.setIcon(new ImageIcon(getClass().getClassLoader().getResource("Icons\\icons8_Cancel_32px.png")));
    }//GEN-LAST:event_jLBLexitMouseExited

    private void jLBLexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLexitMouseClicked
    System.exit(0);
    }//GEN-LAST:event_jLBLexitMouseClicked

    private void jLBLminimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLminimizeMouseEntered
    jLBLminimize.setIcon(new ImageIcon(getClass().getClassLoader().getResource("Icons\\icons8_Minimize_Window_32px_2.png")));
    }//GEN-LAST:event_jLBLminimizeMouseEntered

    private void jLBLminimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLminimizeMouseExited
    jLBLminimize.setIcon(new ImageIcon(getClass().getClassLoader().getResource("Icons\\icons8_Minimize_Window_32px_1.png")));
    }//GEN-LAST:event_jLBLminimizeMouseExited

    private void jLBLminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLminimizeMouseClicked
    this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLBLminimizeMouseClicked

    private void jTFuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFuserKeyPressed
    if(jTFuser.getForeground()!=new Color(200,200,200,255)){
        if(jTFuser.getText().equals("User Name")){
            jTFuser.setText("");
        }
    }
    jTFuser.setForeground(new Color(200,200,200,255));
    }//GEN-LAST:event_jTFuserKeyPressed

    private void jTFuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFuserKeyReleased
    if(jTFuser.getText().isEmpty()){
        jTFuser.setText("User Name");
        jTFuser.setCaretPosition(0);
        jTFuser.setForeground(new Color(125,125,125,255));
    }
    }//GEN-LAST:event_jTFuserKeyReleased

    private void jTFuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuserMousePressed
    jTFuser.setCaretPosition(0);
    }//GEN-LAST:event_jTFuserMousePressed

    private void jPFpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFpassActionPerformed
    
    }//GEN-LAST:event_jPFpassActionPerformed

    private void jTFuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFuserActionPerformed
    
    }//GEN-LAST:event_jTFuserActionPerformed

    private void jPFpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFpassKeyPressed
    if(jPFpass.getForeground()!=new Color(200,200,200)){
        if(jPFpass.getText().equals("Password")){
            jPFpass.setText("");
            if(jTBTNvis.isSelected()){
               jPFpass.setEchoChar((char)0);
            }
            else if(jTBTNvis.isSelected()==false){
               jPFpass.setEchoChar('*');
            }
        }
    }
    jPFpass.setForeground(new Color(200,200,200));
    }//GEN-LAST:event_jPFpassKeyPressed

    private void jPFpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFpassKeyReleased
    if(jPFpass.getText().isEmpty()){
        jPFpass.setText("Password");
        jPFpass.setEchoChar((char)0);
        jPFpass.setCaretPosition(0);
        jPFpass.setForeground(new Color(125,125,125));
    }
    }//GEN-LAST:event_jPFpassKeyReleased

    private void jPFpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPFpassMousePressed
    jPFpass.setCaretPosition(0);
    }//GEN-LAST:event_jPFpassMousePressed

    private void jTBTNvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBTNvisActionPerformed
        if(jTBTNvis.isSelected()){
               jPFpass.setEchoChar((char)0);
               jTBTNvis.setIcon(new ImageIcon(getClass().getClassLoader().getResource("Icons\\icons8_Eye_32px_1.png")));
        }
        else if(jTBTNvis.isSelected()==false){
               jPFpass.setEchoChar('*');
               jTBTNvis.setIcon(new ImageIcon(getClass().getClassLoader().getResource("Icons\\icons8_Invisible_32px_1.png")));
        }
    }//GEN-LAST:event_jTBTNvisActionPerformed

    private void jTBTNvisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBTNvisMouseEntered
    jTBTNvis.setBorderPainted(true);
    }//GEN-LAST:event_jTBTNvisMouseEntered

    private void jTBTNvisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBTNvisMouseExited
    jTBTNvis.setBorderPainted(false);
    }//GEN-LAST:event_jTBTNvisMouseExited

    private void jBTNforgotpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNforgotpassMouseEntered
    jBTNforgotpass.setBorderPainted(true);
    }//GEN-LAST:event_jBTNforgotpassMouseEntered

    private void jBTNforgotpassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNforgotpassMouseExited
    jBTNforgotpass.setBorderPainted(false);
    }//GEN-LAST:event_jBTNforgotpassMouseExited
    Border border=BorderFactory.createLineBorder(new Color(200,200,200),2);
    private void jPsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPsigninMouseEntered
    jPsignin.setBorder(border);
    }//GEN-LAST:event_jPsigninMouseEntered

    private void jPsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPsigninMouseExited
    //similar to remove border
    jPsignin.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_jPsigninMouseExited

    private void jBTNsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNsigninMouseEntered
    jPsignin.setBorder(border);
    }//GEN-LAST:event_jBTNsigninMouseEntered

    private void jBTNsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNsigninMouseExited
    jPsignin.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_jBTNsigninMouseExited

    private void jLBLsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLsigninMouseEntered
    jPsignin.setBorder(border);
    }//GEN-LAST:event_jLBLsigninMouseEntered

    private void jLBLsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLsigninMouseExited
    jPsignin.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_jLBLsigninMouseExited

    private void jLBLsignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLsignupMouseEntered
    jPsignup.setBorder(border);
    }//GEN-LAST:event_jLBLsignupMouseEntered

    private void jLBLsignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLsignupMouseExited
    jPsignup.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_jLBLsignupMouseExited

    private void jBTNsignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNsignupMouseEntered
    jPsignup.setBorder(border);
    }//GEN-LAST:event_jBTNsignupMouseEntered

    private void jBTNsignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNsignupMouseExited
    jPsignup.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_jBTNsignupMouseExited

    private void jPsignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPsignupMouseEntered
    jPsignup.setBorder(border);
    }//GEN-LAST:event_jPsignupMouseEntered

    private void jPsignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPsignupMouseExited
    jPsignup.setBorder(new EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_jPsignupMouseExited

    private void jLBLoskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLoskMouseEntered
    jLBLosk.setIcon(new ImageIcon(getClass().getClassLoader().getResource("Icons\\icons8_Keyboard_64px_2.png")));
    /*
      can also use full location like:
      jLBLosk.setIcon(new ImageIcon("E:\SIVABALAN\Project JAVIS Files\Documentation\COADING\SIGN_IN\public LOGIN_JAVIS2.PNG")));
    in fact if you want to run this project using executable file then change all the file location like this
    it is easy go to edit in menu bar of natbeans and click find, replace
    enter [getClass().getClassLoader().getResource("] *withoutht bracket 
    in find and replace with the Icons folder location in your project's src folder 
    */
    }//GEN-LAST:event_jLBLoskMouseEntered

    private void jLBLoskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLoskMouseExited
    jLBLosk.setIcon(new ImageIcon(getClass().getClassLoader().getResource("Icons\\icons8_Keyboard_64px.png")));    
    }//GEN-LAST:event_jLBLoskMouseExited

    private void jLBLoskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLoskMouseClicked
    try {
            Desktop.getDesktop().open(new File("C:\\Windows\\system32\\osk.exe"));
            //you can open any app with this coading by changing the location
        } 
    catch (IOException ex) {
            Logger.getLogger(LOGIN_JAVIS.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLBLoskMouseClicked

    private void jBTNsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNsignupActionPerformed
    SIGNUP_JAVIS signup= new SIGNUP_JAVIS();
    signup.setVisible(true);
    this.dispose();
    //or this.setVisible(false); for regaining whenever wanted
    }//GEN-LAST:event_jBTNsignupActionPerformed

    private void jLBLsignupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBLsignupMouseReleased
    SIGNUP_JAVIS signup= new SIGNUP_JAVIS();
    signup.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLBLsignupMouseReleased

    private void jPsignupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPsignupMouseReleased
    SIGNUP_JAVIS signup= new SIGNUP_JAVIS();
    signup.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jPsignupMouseReleased

    private void jBTNsigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNsigninMouseClicked
    boolean u=false,p=false;
    if(jTFuser.getText().equals("User Name")){
        JOptionPane.showMessageDialog(null, "Enter a valid User Name \n 'User Name' will not be accepted as an entry", "Invalid User Name", 0,null);
    }else if(jTFuser.getText().equals("")){
        JOptionPane.showMessageDialog(null, "User name is empty!!!", "Invalid User Name", 0,null);
    }else{
        u=true;
    }
    if(jPFpass.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Password is empty!!!", "Invalid password", 0,null);
    }else{
        p=true;
    }
    if(u==true){
        if(p==true){
             try {
                 Class.forName("com.mysql.jdbc.Driver").newInstance();
                 String db_url="jdbc:mysql://localhost:3306/project_JAVIS";
                 Connection conn= DriverManager.getConnection(db_url, "root", "mysql");
                 Statement smt=conn.createStatement();
                 //Getting input data 
                 String username=jTFuser.getText();
                 String Password=jPFpass.getText();
                 
                 //Getting data from the server
                 String sql="select * from clients_manage_string_JAVIS where USER_ID='"+username+"';";
                 ResultSet rs=smt.executeQuery(sql);
                 
                 //Decryption and Encryption of password
                 String encrypted_password="";
                 String brand="";
                 String mrand="";
                 String frand="";
                 String userID="";
                 while(rs.next()){
                 userID=rs.getString("USER_ID");
                 encrypted_password=rs.getString("pass_string");
                 brand=rs.getString("b_string");
                 mrand=rs.getString("m_string");
                 frand=rs.getString("f_string");
                 }
                 int mid=Password.length();
                 String midtext1=Password.substring(0,mid/2);
                 String midtext2=Password.substring(mid/2);
                 String decrypted=brand+midtext1+mrand+midtext2+frand;
                 
                 //Verifing password
                 //Verifing user
                 
                 if(userID.equals("")){
                     JOptionPane.showMessageDialog(null, "User Name not Available", "Unknown user", 0,null);
                 }else{
                 if(encrypted_password.equals(decrypted)){
                     JOptionPane.showMessageDialog(null, "Successfully Logged in"+"\n Welcome Back "+username, "Login successful", 0,new ImageIcon(getClass().getClassLoader().getResource("Icons\\icons8_Good_Quality_48px.png")));
                     JAVIS_OFFICIAL_SITE os=new JAVIS_OFFICIAL_SITE();
                     os.jLBLusername_os.setText(""+userID);
                     os.setVisible(true);
                     os.setLocationRelativeTo(null);
                     os.setSize(1282,629);
                     this.setVisible(false);
                     
                     //updating data
                     try{
                        Class.forName("com.mysql.jdbc.Driver").newInstance();
                        String sql1="update clients_javis set LAST_SIGN_IN=now() where user_id='"+userID+"';";
                        int rc=smt.executeUpdate(sql1);
                        smt.close();
                        conn.close();
   
                     }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Error in Data update :\n"+e);
                    }
                 }else{
                     JOptionPane.showMessageDialog(null, "Sorry the password did not match", "Incorrect Password", 0,null);
                 }
                 }
                 rs.close();
                 smt.close();
                 conn.close();

                 }
                catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Error in connection to the server :\n"+e);
                }
        }
    }
    }//GEN-LAST:event_jBTNsigninMouseClicked
int xx,xy;
    private void jPbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPbackMousePressed
    xx = evt.getX();
    xy = evt.getY();
    }//GEN-LAST:event_jPbackMousePressed

    private void jPbackMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPbackMouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPbackMouseDragged
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN_JAVIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN_JAVIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN_JAVIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN_JAVIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_JAVIS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNforgotpass;
    private javax.swing.JButton jBTNsignin;
    private javax.swing.JButton jBTNsignup;
    private javax.swing.JLabel jLBLback;
    private javax.swing.JLabel jLBLdysc1;
    private javax.swing.JLabel jLBLdysc2;
    private javax.swing.JLabel jLBLexit;
    private javax.swing.JLabel jLBLicon;
    private javax.swing.JLabel jLBLlogin;
    private javax.swing.JLabel jLBLminimize;
    private javax.swing.JLabel jLBLosk;
    private javax.swing.JLabel jLBLsignin;
    private javax.swing.JLabel jLBLsignup;
    private javax.swing.JLabel jLBLtaskbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPFpass;
    private javax.swing.JPanel jPback;
    private javax.swing.JPanel jPlogin;
    private javax.swing.JPanel jPsignin;
    private javax.swing.JPanel jPsignup;
    private javax.swing.JSeparator jSpass;
    private javax.swing.JSeparator jSuser;
    private javax.swing.JToggleButton jTBTNvis;
    private javax.swing.JTextField jTFuser;
    // End of variables declaration//GEN-END:variables

}
